environment: prod

image:
  repository: aizeprodacr.azurecr.io/backend-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2
replicaCountInactive: 2

blueGreen:
  activeColor: blue
  inactiveColor: green

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: backend.aize.com
      paths:
        - /
  tls:
    - secretName: backend-staging-tls
      hosts:
        - backend.aize.com

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 5
