apiVersion: v1
kind: Service
metadata:
  name: backend-service-active
  labels:
    app: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend-service
    color: {{ .Values.blueGreen.activeColor | default "blue" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}
