apiVersion: v1
kind: Service
metadata:
  name: frontend-service-active
  labels:
    app: frontend-service
spec:
  selector:
    app: frontend-service
    color: {{ .Values.blueGreen.activeColor | default "blue" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: {{ .Values.service.type }}
